# Generated by Django 4.1.5 on 2023-02-01 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_acheter'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheter',
            name='date_achat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
