# Generated by Django 4.1.5 on 2023-02-01 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_acheter_date_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevision',
            name='date_achat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
