# Generated by Django 4.1.5 on 2023-02-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_prevision_date_achat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
    ]
