# Generated by Django 4.1.5 on 2023-02-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prevision',
            name='unite_price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prevision',
            name='date_achat',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prevision',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
